var games = 
[
  {
    "id": "100",
    "date": "1/28/1996",
    "site": "Sun Devil Stadium",
    "home": "Dallas Cowboys",
    "visitor": "Pittsburgh Steelers",
    "r": "R. Cashion",
    "u": "J. Keck",
    "h": "P. Weidner",
    "l": "D. Orem",
    "s": "B. Carollo",
    "f": "D. Hakes",
    "b": "D. Creed"
  },
  {
    "id": "468",
    "date": "8/31/2018",
    "site": "West Hills",
    "home": "West Hills",
    "visitor": "Diablo Valley",
    "r": "J. Taplin",
    "u": "L. Salazar",
    "h": "C. Burrell",
    "l": "R. Clark",
    "s": "O. Salazar",
    "f": "B. Snyder",
    "b": "R. Cazares"
  },
  {
    "id": "469",
    "date": "9/1/2018",
    "site": "Butte",
    "home": "Butte",
    "visitor": "Delta",
    "r": "J. Johnson",
    "u": "T. Gomez",
    "h": "C. Felkins",
    "l": "J. Kennedy",
    "s": "B. Steinmann",
    "f": "J. Rogers",
    "b": "K. Erskine"
  },
  {
    "id": "470",
    "date": "9/1/2018",
    "site": "Contra Costa",
    "home": "Contra Costa",
    "visitor": "Cabrillo",
    "r": "J. McGeough",
    "u": "S. Tate",
    "h": "D. Johnson",
    "l": "L. Mcinerney",
    "s": "A. Jensen",
    "f": "A. Croskey",
    "b": "P. Campana"
  },
  {
    "id": "471",
    "date": "9/1/2018",
    "site": "DeAnza",
    "home": "DeAnza",
    "visitor": "Reedley",
    "r": "S. Carter",
    "u": "M. Morris",
    "h": "L. Null",
    "l": "D. Peterson",
    "s": "N. Pontecorvo",
    "f": "K. Heard",
    "b": "O. Sangameswara"
  },
  {
    "id": "472",
    "date": "9/1/2018",
    "site": "Feather River College",
    "home": "Feather River",
    "visitor": "Sequoias",
    "r": "E. Hintz",
    "u": "A. Siderius",
    "h": "T. Frugoli",
    "l": "M. Averett",
    "s": "J. Mcclenahan",
    "f": "T. Morris",
    "b": "R. Polito"
  },
  {
    "id": "473",
    "date": "9/1/2018",
    "site": "Redwoods",
    "home": "Redwoods",
    "visitor": "Monterey",
    "r": "K. Mason",
    "u": "D. Wellington",
    "h": "L. Weiper",
    "l": "J. Castagnola",
    "s": "S. Young",
    "f": "C. Hayes",
    "b": "E. Hirsch"
  },
  {
    "id": "474",
    "date": "9/1/2018",
    "site": "San Francisco City College",
    "home": "San Francisco",
    "visitor": "Sierra",
    "r": "M. Aldrich",
    "u": "P. Burford",
    "h": "R. Nelson",
    "l": "J. Roberts",
    "s": "P. Schutt",
    "f": "R. Davenport",
    "b": "M. Fowler"
  },
  {
    "id": "475",
    "date": "9/1/2018",
    "site": "San Mateo",
    "home": "San Mateo",
    "visitor": "Siskiyous",
    "r": "J. Galvin",
    "u": "M. Fagan",
    "h": "B. Werner",
    "l": "A. Schmitz",
    "s": "J. Springer",
    "f": "C. Guinnip",
    "b": "J. Freeman"
  },
  {
    "id": "476",
    "date": "9/1/2018",
    "site": "American River College",
    "home": "American River",
    "visitor": "Sacramento",
    "r": "C. Miers",
    "u": "M. Tomlinson",
    "h": "J. Delgado",
    "l": "________ ",
    "s": "R. Maddox",
    "f": "B. Olesen",
    "b": "K. Carver"
  },
  {
    "id": "597",
    "date": "9/1/2018",
    "site": "Fresno (Radcliffe Stadium)",
    "home": "Fresno",
    "visitor": "Santa Rosa",
    "r": "M. Merritt",
    "u": "A. Phillips",
    "h": "D. Pepe",
    "l": "D. Coelho",
    "s": "T. Pinedo",
    "f": "O. Salazar",
    "b": "J. Bondi"
  },
  {
    "id": "477",
    "date": "9/1/2018",
    "site": "Chabot",
    "home": "Chabot",
    "visitor": "Shasta",
    "r": "J. Bigler",
    "u": "P. Burford",
    "h": "D. Jones",
    "l": "R. Medeiros",
    "s": "D. Velleman",
    "f": "K. Thomas",
    "b": "A. Smart"
  },
  {
    "id": "478",
    "date": "9/1/2018",
    "site": "Los Medanos",
    "home": "Los Medanos",
    "visitor": "Gavilan",
    "r": "J. O'Neil",
    "u": "A. Gordillo",
    "h": "T. Bennett",
    "l": "D. Wood",
    "s": "D. Evans",
    "f": "N. Stoll",
    "b": "T. Brendlin"
  },
  {
    "id": "479",
    "date": "9/1/2018",
    "site": "Yuba",
    "home": "Yuba",
    "visitor": "Hartnell",
    "r": "D. Burch",
    "u": "J. Martin",
    "h": "L. Rogers",
    "l": "A. Juarez",
    "s": "C. Sindel",
    "f": "Z. Snell",
    "b": "J. Nagle"
  },
  {
    "id": "480",
    "date": "9/1/2018",
    "site": "Foothill College",
    "home": "Foothill",
    "visitor": "Merced",
    "r": "K. Blevens",
    "u": "T. Daurelio",
    "h": "J. Brooks",
    "l": "T. Welch",
    "s": "N. Pontecorvo",
    "f": "T. Igbinedion",
    "b": "M. Dunn"
  },
  {
    "id": "481",
    "date": "9/1/2018",
    "site": "Modesto",
    "home": "Modesto",
    "visitor": "Laney",
    "r": "K. Udell",
    "u": "S. Jones",
    "h": "A. Garcia",
    "l": "S. Ramos",
    "s": "J. Mendoza",
    "f": "P. Robinson",
    "b": "M. Dominguez"
  },
  {
    "id": "482",
    "date": "9/7/2018",
    "site": "Diablo Valley",
    "home": "Diablo Valley",
    "visitor": "Feather River",
    "r": "M. Merritt",
    "u": "P. Burford",
    "h": "J. Delgado",
    "l": "R. Medeiros",
    "s": "N. Pontecorvo",
    "f": "J. Fugate",
    "b": "J. Bondi"
  },
  {
    "id": "492",
    "date": "9/7/2018",
    "site": "Sacramento",
    "home": "Sacramento",
    "visitor": "San Francisco",
    "r": "G. Robinson",
    "u": "M. Tomlinson",
    "h": "R. Robeson",
    "l": "C. Miers",
    "s": "J. Johnson",
    "f": "J. McGeough",
    "b": "M. Dominguez"
  },
  {
    "id": "483",
    "date": "9/7/2018",
    "site": "Laney",
    "home": "Laney",
    "visitor": "American River",
    "r": "B. Michelson",
    "u": "B. O'Driscoll",
    "h": "M. Aldrich",
    "l": "D. Jones",
    "s": "J. Decker",
    "f": "P. Schutt",
    "b": "M. Fowler"
  },
  {
    "id": "484",
    "date": "9/8/2018",
    "site": "Shasta",
    "home": "Shasta",
    "visitor": "West Hills",
    "r": "________ ",
    "u": "________ ",
    "h": "________ ",
    "l": "________ ",
    "s": "________ ",
    "f": "________ ",
    "b": "________ "
  },
  {
    "id": "485",
    "date": "9/8/2018",
    "site": "Delta",
    "home": "Delta",
    "visitor": "San Mateo",
    "r": "D. Burch",
    "u": "P. Burford",
    "h": "K. Govea",
    "l": "R. Beeman",
    "s": "D. Mullens",
    "f": "K. Thomas",
    "b": "J. Nardi"
  },
  {
    "id": "486",
    "date": "9/8/2018",
    "site": "San Jose",
    "home": "San Jose",
    "visitor": "Los Medanos",
    "r": "K. Leffle",
    "u": "M. Morris",
    "h": "D. Coelho",
    "l": "J. Roberts",
    "s": "E. Hawkins",
    "f": "J. Fugate",
    "b": "D. Velleman"
  },
  {
    "id": "487",
    "date": "9/8/2018",
    "site": "Sierra",
    "home": "Sierra",
    "visitor": "Modesto",
    "r": "J. Galvin",
    "u": "A. Phillips",
    "h": "A. Schmitz",
    "l": "D. Dean",
    "s": "J. Rogers",
    "f": "E. Joe",
    "b": "R. Polito"
  },
  {
    "id": "616",
    "date": "9/8/2018",
    "site": "Reedley (Reedley High School)",
    "home": "Reedley",
    "visitor": "Yuba",
    "r": "R. Mayabb",
    "u": "T. Sparkes",
    "h": "A. Garcia",
    "l": "C. Burrell",
    "s": "H. Johnson",
    "f": "J. Mendoza",
    "b": "O. Salazar"
  },
  {
    "id": "611",
    "date": "9/8/2018",
    "site": "Gavilan (Gilroy High School)",
    "home": "Gavilan",
    "visitor": "Redwoods",
    "r": "S. Carter",
    "u": "T. Daurelio",
    "h": "D. Johnson",
    "l": "R. Nelson",
    "s": "T. Igbinedion",
    "f": "B. Olesen",
    "b": "O. Sangameswara"
  },
  {
    "id": "489",
    "date": "9/8/2018",
    "site": "Santa Rosa Junior College",
    "home": "Santa Rosa",
    "visitor": "Butte",
    "r": "K. Mason",
    "u": "D. Wellington",
    "h": "R. Mora",
    "l": "T. Welch",
    "s": "M. Fowler",
    "f": "C. Hayes",
    "b": "E. Hirsch"
  },
  {
    "id": "490",
    "date": "9/8/2018",
    "site": "Merced",
    "home": "Merced",
    "visitor": "DeAnza",
    "r": "K. Blevens",
    "u": "C. Hickman",
    "h": "J. Brooks",
    "l": "J. Delgado",
    "s": "T. Pinedo",
    "f": "J. Springer",
    "b": "J. Freeman"
  },
  {
    "id": "491",
    "date": "9/8/2018",
    "site": "Monterey",
    "home": "Monterey",
    "visitor": "Contra Costa",
    "r": "M. Younkin",
    "u": "L. Salazar",
    "h": "D. Peterson",
    "l": "T. Bennett",
    "s": "D. Evans",
    "f": "N. Stoll",
    "b": "A. Smart"
  },
  {
    "id": "598",
    "date": "9/8/2018",
    "site": "Hartnell (Rabobank Stadium)",
    "home": "Hartnell",
    "visitor": "Foothill",
    "r": "J. O'Neil",
    "u": "M. Fagan",
    "h": "B. Werner",
    "l": "D. Wood",
    "s": "C. Coelho",
    "f": "R. Davenport",
    "b": "M. Dominguez"
  },
  {
    "id": "607",
    "date": "9/8/2018",
    "site": "Sequoias (Mineral King Bowl)",
    "home": "Sequoias",
    "visitor": "Chabot",
    "r": "K. Udell",
    "u": "B. Alcantar",
    "h": "D. Pepe",
    "l": "R. Clark",
    "s": "J. Canales",
    "f": "B. Snyder",
    "b": "R. Cazares"
  },
  {
    "id": "493",
    "date": "9/14/2018",
    "site": "Diablo Valley",
    "home": "Diablo Valley",
    "visitor": "Sacramento",
    "r": "J. McGeough",
    "u": "A. Phillips",
    "h": "L. Rogers",
    "l": "A. Juarez",
    "s": "J. Springer",
    "f": "P. Campana",
    "b": "J. Freeman"
  },
  {
    "id": "608",
    "date": "9/15/2018",
    "site": "Sequoias (Mineral King Bowl)",
    "home": "Sequoias",
    "visitor": "Siskiyous",
    "r": "K. Blevens",
    "u": "L. Salazar",
    "h": "C. Burrell",
    "l": "R. Clark",
    "s": "K. Heard",
    "f": "B. Snyder",
    "b": "O. Salazar"
  },
  {
    "id": "494",
    "date": "9/15/2018",
    "site": "Contra Costa",
    "home": "Contra Costa",
    "visitor": "Reedley",
    "r": "D. Burch",
    "u": "B. Collins",
    "h": "J. Castagnola",
    "l": "T. Welch",
    "s": "N. Pontecorvo",
    "f": "D. Mullens",
    "b": "M. Fowler"
  },
  {
    "id": "495",
    "date": "9/15/2018",
    "site": "DeAnza",
    "home": "DeAnza",
    "visitor": "Gavilan",
    "r": "B. Michelson",
    "u": "B. Alcantar",
    "h": "D. Peterson",
    "l": "R. Nelson",
    "s": "K. Thomas",
    "f": "P. Schutt",
    "b": "M. Dunn"
  },
  {
    "id": "496",
    "date": "9/15/2018",
    "site": "Redwoods",
    "home": "Redwoods",
    "visitor": "Hartnell",
    "r": "R. Chavez",
    "u": "D. Wellington",
    "h": "R. Klumph",
    "l": "R. Robles",
    "s": "S. Young",
    "f": "J. Johnson",
    "b": "B. Pettengill"
  },
  {
    "id": "497",
    "date": "9/15/2018",
    "site": "San Francisco City College",
    "home": "San Francisco",
    "visitor": "Modesto",
    "r": "M. Younkin",
    "u": "P. Burford",
    "h": "T. Frugoli",
    "l": "A. Schmitz",
    "s": "N. Stoll",
    "f": "D. Evans",
    "b": "O. Sangameswara"
  },
  {
    "id": "498",
    "date": "9/15/2018",
    "site": "West Hills",
    "home": "West Hills",
    "visitor": "Sierra",
    "r": "K. Udell",
    "u": "T. Sparkes",
    "h": "D. Loden",
    "l": "J. Delgado",
    "s": "H. Johnson",
    "f": "B. Olesen",
    "b": "J. Bondi"
  },
  {
    "id": "499",
    "date": "9/15/2018",
    "site": "Feather River College",
    "home": "Feather River",
    "visitor": "Laney",
    "r": "E. Hintz",
    "u": "E. Perez",
    "h": "J. Tafelmeyer",
    "l": "G. Dieringer",
    "s": "J. Springer",
    "f": "T. Morris",
    "b": "K. Carver"
  },
  {
    "id": "599",
    "date": "9/15/2018",
    "site": "Fresno (Radcliffe Stadium)",
    "home": "Fresno",
    "visitor": "Butte",
    "r": "R. Mayabb",
    "u": "S. Tate",
    "h": "J. Brooks",
    "l": "S. Ramos",
    "s": "A. Jensen",
    "f": "P. Robinson",
    "b": "P. Campana"
  },
  {
    "id": "500",
    "date": "9/15/2018",
    "site": "American River College",
    "home": "American River",
    "visitor": "San Mateo",
    "r": "J. McGeough",
    "u": "A. Siderius",
    "h": "A. Garcia",
    "l": "M. Averett",
    "s": "R. Polito",
    "f": "J. Mcclenahan",
    "b": "K. Erskine"
  },
  {
    "id": "501",
    "date": "9/15/2018",
    "site": "Chabot",
    "home": "Chabot",
    "visitor": "Delta",
    "r": "G. Robinson",
    "u": "A. Gordillo",
    "h": "R. Medeiros",
    "l": "D. Jones",
    "s": "A. Croskey",
    "f": "E. Joe",
    "b": "T. Brendlin"
  },
  {
    "id": "502",
    "date": "9/15/2018",
    "site": "Los Medanos",
    "home": "Los Medanos",
    "visitor": "Cabrillo",
    "r": "K. Leffle",
    "u": "B. Wilson",
    "h": "R. Beeman",
    "l": "K. Govea",
    "s": "E. Hawkins",
    "f": "C. Hayes",
    "b": "J. Bigler"
  },
  {
    "id": "503",
    "date": "9/15/2018",
    "site": "Shasta",
    "home": "Shasta",
    "visitor": "Santa Rosa",
    "r": "J. Galvin",
    "u": "M. Fagan",
    "h": "B. Werner",
    "l": "V. Wilson",
    "s": "C. Sindel",
    "f": "Z. Snell",
    "b": "J. Nagle"
  },
  {
    "id": "504",
    "date": "9/15/2018",
    "site": "Yuba",
    "home": "Yuba",
    "visitor": "Merced",
    "r": "R. Wright",
    "u": "J. Martin",
    "h": "C. Felkins",
    "l": "J. Kennedy",
    "s": "B. Steinmann",
    "f": "E. Valencia",
    "b": "J. Freeman"
  },
  {
    "id": "505",
    "date": "9/15/2018",
    "site": "Foothill College",
    "home": "Foothill",
    "visitor": "San Jose",
    "r": "S. Carter",
    "u": "B. O'Driscoll",
    "h": "D. Johnson",
    "l": "C. Coelho",
    "s": "T. Igbinedion",
    "f": "T. Pinedo",
    "b": "A. Smart"
  },
  {
    "id": "506",
    "date": "9/21/2018",
    "site": "Laney",
    "home": "Laney",
    "visitor": "West Hills",
    "r": "J. Bigler",
    "u": "M. Morris",
    "h": "J. Spence",
    "l": "R. Nelson",
    "s": "A. Jensen",
    "f": "D. Velleman",
    "b": "M. Dunn"
  },
  {
    "id": "507",
    "date": "9/22/2018",
    "site": "Butte",
    "home": "Butte",
    "visitor": "San Francisco",
    "r": "D. Burch",
    "u": "A. Siderius",
    "h": "A. Schmitz",
    "l": "J. Kennedy",
    "s": "K. Erskine",
    "f": "Z. Snell",
    "b": "J. Nagle"
  },
  {
    "id": "508",
    "date": "9/22/2018",
    "site": "Delta",
    "home": "Delta",
    "visitor": "Feather River",
    "r": "M. Merritt",
    "u": "B. Alcantar",
    "h": "K. Govea",
    "l": "R. Beeman",
    "s": "J. Springer",
    "f": "O. Salazar",
    "b": "M. Dominguez"
  },
  {
    "id": "509",
    "date": "9/22/2018",
    "site": "Redwoods",
    "home": "Redwoods",
    "visitor": "Contra Costa",
    "r": "J. McGeough",
    "u": "B. Wilson",
    "h": "L. Mcinerney",
    "l": "D. Jones",
    "s": "K. Thomas",
    "f": "N. Pontecorvo",
    "b": "P. Campana"
  },
  {
    "id": "510",
    "date": "9/22/2018",
    "site": "San Jose",
    "home": "San Jose",
    "visitor": "Merced",
    "r": "B. Michelson",
    "u": "A. Gordillo",
    "h": "T. Bennett",
    "l": "R. Robeson",
    "s": "T. Pinedo",
    "f": "M. Dunn",
    "b": "M. Fowler"
  },
  {
    "id": "511",
    "date": "9/22/2018",
    "site": "Santa Rosa Junior College",
    "home": "Santa Rosa",
    "visitor": "Sequoias",
    "r": "M. Aldrich",
    "u": "B. O'Driscoll",
    "h": "S. Young",
    "l": "L. Weiper",
    "s": "P. Schutt",
    "f": "C. Hayes",
    "b": "E. Hirsch"
  },
  {
    "id": "512",
    "date": "9/22/2018",
    "site": "Sierra",
    "home": "Sierra",
    "visitor": "Diablo Valley",
    "r": "K. Leffle",
    "u": "M. Fagan",
    "h": "D. Coelho",
    "l": "D. Pepe",
    "s": "T. Morris",
    "f": "C. Sindel",
    "b": "R. Polito"
  },
  {
    "id": "513",
    "date": "9/22/2018",
    "site": "Siskiyous",
    "home": "Siskiyous",
    "visitor": "Chabot",
    "r": "R. Chavez",
    "u": "A. Phillips",
    "h": "E. Watson",
    "l": "D. Dean",
    "s": "B. Steinmann",
    "f": "R. Maddox",
    "b": "B. Pettengill"
  },
  {
    "id": "514",
    "date": "9/22/2018",
    "site": "Yuba",
    "home": "Yuba",
    "visitor": "Los Medanos",
    "r": "R. Wright",
    "u": "T. Gomez",
    "h": "C. Felkins",
    "l": "L. Rogers",
    "s": "J. Rogers",
    "f": "C. Hanna",
    "b": "J. Johnson"
  },
  {
    "id": "617",
    "date": "9/22/2018",
    "site": "Reedley (Reedley High School)",
    "home": "Reedley",
    "visitor": "Foothill",
    "r": "K. Udell",
    "u": "C. Hickman",
    "h": "R. Clark",
    "l": "J. Brooks",
    "s": "J. Canales",
    "f": "B. Snyder",
    "b": "R. Cazares"
  },
  {
    "id": "612",
    "date": "9/22/2018",
    "site": "Gavilan (Gilroy High School)",
    "home": "Gavilan",
    "visitor": "Monterey",
    "r": "R. Mayabb",
    "u": "T. Sparkes",
    "h": "D. Johnson",
    "l": "D. Wood",
    "s": "T. Igbinedion",
    "f": "H. Johnson",
    "b": "A. Smart"
  },
  {
    "id": "515",
    "date": "9/22/2018",
    "site": "San Mateo",
    "home": "San Mateo",
    "visitor": "Fresno",
    "r": "K. Mason",
    "u": "D. Wellington",
    "h": "J. Castagnola",
    "l": "A. Garcia",
    "s": "D. Velleman",
    "f": "E. Hawkins",
    "b": "J. Bondi"
  },
  {
    "id": "516",
    "date": "9/22/2018",
    "site": "Cabrillo College",
    "home": "Cabrillo",
    "visitor": "Hartnell",
    "r": "J. O'Neil",
    "u": "T. Daurelio",
    "h": "J. Roberts",
    "l": "R. Nelson",
    "s": "R. Davenport",
    "f": "C. Coelho",
    "b": "O. Sangameswara"
  },
  {
    "id": "517",
    "date": "9/22/2018",
    "site": "Sacramento",
    "home": "Sacramento",
    "visitor": "Shasta",
    "r": "C. Miers",
    "u": "E. Perez",
    "h": "T. Frugoli",
    "l": "M. Averett",
    "s": "G. Dieringer",
    "f": "C. Guinnip",
    "b": "K. Carver"
  },
  {
    "id": "518",
    "date": "9/22/2018",
    "site": "Modesto",
    "home": "Modesto",
    "visitor": "American River",
    "r": "G. Robinson",
    "u": "S. Tate",
    "h": "R. Medeiros",
    "l": "S. Ramos",
    "s": "B. Olesen",
    "f": "A. Croskey",
    "b": "J. Freeman"
  },
  {
    "id": "520",
    "date": "9/28/2018",
    "site": "Laney",
    "home": "Laney",
    "visitor": "Butte",
    "r": "M. Aldrich",
    "u": "P. Burford",
    "h": "P. Farley",
    "l": "J. Delgado",
    "s": "J. Springer",
    "f": "J. Decker",
    "b": "J. Freeman"
  },
  {
    "id": "622",
    "date": "9/29/2018",
    "site": "Sequoias (Mineral King Bowl)",
    "home": "Sequoias",
    "visitor": "Shasta",
    "r": "J. Taplin",
    "u": "L. Salazar",
    "h": "A. Garcia",
    "l": "S. Ramos",
    "s": "J. Canales",
    "f": "B. Snyder",
    "b": "R. Cazares"
  },
  {
    "id": "618",
    "date": "9/29/2018",
    "site": "Reedley (Reedley High School)",
    "home": "Reedley",
    "visitor": "Cabrillo",
    "r": "K. Blevens",
    "u": "M. Tomlinson",
    "h": "C. Burrell",
    "l": "J. Spence",
    "s": "T. Pinedo",
    "f": "K. Heard",
    "b": "R. Mayabb"
  },
  {
    "id": "521",
    "date": "9/29/2018",
    "site": "DeAnza",
    "home": "DeAnza",
    "visitor": "Redwoods",
    "r": "M. Merritt",
    "u": "C. Hickman",
    "h": "J. Delgado",
    "l": "D. Coelho",
    "s": "C. Coelho",
    "f": "R. Davenport",
    "b": "D. Velleman"
  },
  {
    "id": "522",
    "date": "9/29/2018",
    "site": "Siskiyous",
    "home": "Siskiyous",
    "visitor": "San Francisco",
    "r": "R. Chavez",
    "u": "T. Gomez",
    "h": "R. Klumph",
    "l": "C. Felkins",
    "s": "K. Kronser",
    "f": "J. Johnson",
    "b": "K. Erskine"
  },
  {
    "id": "523",
    "date": "9/29/2018",
    "site": "Feather River College",
    "home": "Feather River",
    "visitor": "Santa Rosa",
    "r": "J. Galvin",
    "u": "S. Jones",
    "h": "________ ",
    "l": "A. Juarez",
    "s": "C. Guinnip",
    "f": "B. Steinmann",
    "b": "J. Freeman"
  },
  {
    "id": "519",
    "date": "9/29/2018",
    "site": "Diablo Valley",
    "home": "Diablo Valley",
    "visitor": "Delta",
    "r": "G. Robinson",
    "u": "D. Preciado",
    "h": "D. Coelho",
    "l": "________ ",
    "s": "P. Schutt",
    "f": "E. Hawkins",
    "b": "D. Velleman"
  },
  {
    "id": "524",
    "date": "9/29/2018",
    "site": "American River College",
    "home": "American River",
    "visitor": "Fresno",
    "r": "R. Wright",
    "u": "A. Phillips",
    "h": "J. Kennedy",
    "l": "R. Mora",
    "s": "A. Jensen",
    "f": "K. Carver",
    "b": "T. Brendlin"
  },
  {
    "id": "525",
    "date": "9/29/2018",
    "site": "Chabot",
    "home": "Chabot",
    "visitor": "West Hills",
    "r": "K. Leffle",
    "u": "B. Wilson",
    "h": "L. Mcinerney",
    "l": "R. Robeson",
    "s": "C. Sindel",
    "f": "J. Springer",
    "b": "M. Dominguez"
  },
  {
    "id": "526",
    "date": "9/29/2018",
    "site": "Merced",
    "home": "Merced",
    "visitor": "Contra Costa",
    "r": "J. McGeough",
    "u": "B. Collins",
    "h": "D. Pepe",
    "l": "K. Govea",
    "s": "B. Olesen",
    "f": "D. Mullens",
    "b": "J. Bigler"
  },
  {
    "id": "527",
    "date": "9/29/2018",
    "site": "Monterey",
    "home": "Monterey",
    "visitor": "San Jose",
    "r": "M. Younkin",
    "u": "M. Morris",
    "h": "D. Peterson",
    "l": "D. Wood",
    "s": "N. Pontecorvo",
    "f": "A. Croskey",
    "b": "M. Fowler"
  },
  {
    "id": "528",
    "date": "9/29/2018",
    "site": "Sacramento",
    "home": "Sacramento",
    "visitor": "Sierra",
    "r": "D. Burch",
    "u": "M. Fagan",
    "h": "D. Dean",
    "l": "J. Tafelmeyer",
    "s": "G. Dieringer",
    "f": "T. Morris",
    "b": "J. Aragon"
  },
  {
    "id": "600",
    "date": "9/29/2018",
    "site": "Hartnell (Rabobank Stadium)",
    "home": "Hartnell",
    "visitor": "Gavilan",
    "r": "B. Michelson",
    "u": "B. O'Driscoll",
    "h": "T. Bennett",
    "l": "J. Brooks",
    "s": "P. Robinson",
    "f": "O. Salazar",
    "b": "J. Bondi"
  },
  {
    "id": "529",
    "date": "9/29/2018",
    "site": "Foothill College",
    "home": "Foothill",
    "visitor": "Yuba",
    "r": "J. O'Neil",
    "u": "T. Daurelio",
    "h": "D. Johnson",
    "l": "R. Nelson",
    "s": "D. Evans",
    "f": "N. Stoll",
    "b": "O. Sangameswara"
  },
  {
    "id": "530",
    "date": "9/29/2018",
    "site": "Modesto",
    "home": "Modesto",
    "visitor": "San Mateo",
    "r": "C. Miers",
    "u": "B. Alcantar",
    "h": "B. Werner",
    "l": "V. Wilson",
    "s": "E. Joe",
    "f": "C. Hayes",
    "b": "________ "
  },
  {
    "id": "531",
    "date": "10/6/2018",
    "site": "Cabrillo College",
    "home": "Cabrillo",
    "visitor": "Redwoods",
    "r": "J. O'Neil",
    "u": "M. Tomlinson",
    "h": "D. Coelho",
    "l": "L. Null",
    "s": "D. Evans",
    "f": "N. Stoll",
    "b": "A. Smart"
  },
  {
    "id": "532",
    "date": "10/6/2018",
    "site": "Contra Costa",
    "home": "Contra Costa",
    "visitor": "San Jose",
    "r": "S. Carter",
    "u": "D. Wellington",
    "h": "J. Castagnola",
    "l": "T. Welch",
    "s": "K. Thomas",
    "f": "R. Robeson",
    "b": "M. Fowler"
  },
  {
    "id": "533",
    "date": "10/6/2018",
    "site": "Los Medanos",
    "home": "Los Medanos",
    "visitor": "DeAnza",
    "r": "G. Robinson",
    "u": "S. Tate",
    "h": "A. Schmitz",
    "l": "T. Frugoli",
    "s": "G. Dieringer",
    "f": "T. Morris",
    "b": "D. Velleman"
  },
  {
    "id": "534",
    "date": "10/6/2018",
    "site": "Yuba",
    "home": "Yuba",
    "visitor": "Monterey",
    "r": "J. Galvin",
    "u": "T. Gomez",
    "h": "J. Kennedy",
    "l": "V. Wilson",
    "s": "Z. Snell",
    "f": "C. Guinnip",
    "b": "K. Erskine"
  },
  {
    "id": "488",
    "date": "10/6/2018",
    "site": "Siskiyous",
    "home": "Siskiyous",
    "visitor": "Fresno",
    "r": "________ ",
    "u": "________ ",
    "h": "________ ",
    "l": "________ ",
    "s": "________ ",
    "f": "________ ",
    "b": "________ "
  },
  {
    "id": "613",
    "date": "10/6/2018",
    "site": "Gavilan (Gilroy High School)",
    "home": "Gavilan",
    "visitor": "Foothill",
    "r": "M. Younkin",
    "u": "B. Collins",
    "h": "D. Peterson",
    "l": "T. Bennett",
    "s": "K. Heard",
    "f": "T. Pinedo",
    "b": "J. Bondi"
  },
  {
    "id": "535",
    "date": "10/12/2018",
    "site": "West Hills",
    "home": "West Hills",
    "visitor": "Sacramento",
    "r": "R. Mayabb",
    "u": "T. Sparkes",
    "h": "J. Delgado",
    "l": "S. Ramos",
    "s": "H. Johnson",
    "f": "K. Heard",
    "b": "J. Bondi"
  },
  {
    "id": "536",
    "date": "10/13/2018",
    "site": "Butte",
    "home": "Butte",
    "visitor": "Feather River",
    "r": "R. Wright",
    "u": "T. Gomez",
    "h": "C. Felkins",
    "l": "J. Kennedy",
    "s": "J. Rogers",
    "f": "B. Steinmann",
    "b": "J. Nagle"
  },
  {
    "id": "537",
    "date": "10/13/2018",
    "site": "Contra Costa",
    "home": "Contra Costa",
    "visitor": "DeAnza",
    "r": "G. Robinson",
    "u": "D. Wellington",
    "h": "D. Jones",
    "l": "S. Young",
    "s": "C. Hayes",
    "f": "N. Pontecorvo",
    "b": "E. Hirsch"
  },
  {
    "id": "538",
    "date": "10/13/2018",
    "site": "Merced",
    "home": "Merced",
    "visitor": "Monterey",
    "r": "D. Burch",
    "u": "A. Phillips",
    "h": "J. Brooks",
    "l": "A. Garcia",
    "s": "D. Mullens",
    "f": "J. Springer",
    "b": "P. Campana"
  },
  {
    "id": "539",
    "date": "10/13/2018",
    "site": "Redwoods",
    "home": "Redwoods",
    "visitor": "Los Medanos",
    "r": "B. Michelson",
    "u": "D. Preciado",
    "h": "M. Aldrich",
    "l": "P. Farley",
    "s": "E. Hawkins",
    "f": "P. Schutt",
    "b": "M. Fowler"
  },
  {
    "id": "540",
    "date": "10/13/2018",
    "site": "San Jose",
    "home": "San Jose",
    "visitor": "Hartnell",
    "r": "J. McGeough",
    "u": "B. Wilson",
    "h": "T. Bennett",
    "l": "L. Null",
    "s": "A. Croskey",
    "f": "D. Velleman",
    "b": "T. Brendlin"
  },
  {
    "id": "541",
    "date": "10/13/2018",
    "site": "San Mateo",
    "home": "San Mateo",
    "visitor": "Santa Rosa",
    "r": "E. Hintz",
    "u": "E. Perez",
    "h": "M. Averett",
    "l": "A. Schmitz",
    "s": "J. Mcclenahan",
    "f": "R. Polito",
    "b": "K. Carver"
  },
  {
    "id": "601",
    "date": "10/13/2018",
    "site": "Fresno (Radcliffe Stadium)",
    "home": "Fresno",
    "visitor": "Delta",
    "r": "J. Taplin",
    "u": "C. Hickman",
    "h": "R. Clark",
    "l": "C. Burrell",
    "s": "T. Pinedo",
    "f": "K. Heard",
    "b": "R. Cazares"
  },
  {
    "id": "621",
    "date": "10/13/2018",
    "site": "San Francisco City College",
    "home": "San Francisco",
    "visitor": "Laney",
    "r": "K. Leffle",
    "u": "M. Morris",
    "h": "P. Llewellyn",
    "l": "R. Robeson",
    "s": "A. Jensen",
    "f": "K. Thomas",
    "b": "J. Bigler"
  },
  {
    "id": "543",
    "date": "10/13/2018",
    "site": "American River College",
    "home": "American River",
    "visitor": "Siskiyous",
    "r": "K. Mason",
    "u": "L. Salazar",
    "h": "D. Dean",
    "l": "L. Mcinerney",
    "s": "P. Robinson",
    "f": "C. Sindel",
    "b": "J. Freeman"
  },
  {
    "id": "614",
    "date": "10/13/2018",
    "site": "Gavilan (Gilroy High School)",
    "home": "Gavilan",
    "visitor": "Reedley",
    "r": "J. O'Neil",
    "u": "P. Burford",
    "h": "R. Nelson",
    "l": "D. Wood",
    "s": "D. Evans",
    "f": "N. Stoll",
    "b": "A. Smart"
  },
  {
    "id": "542",
    "date": "10/13/2018",
    "site": "Shasta",
    "home": "Shasta",
    "visitor": "Sierra",
    "r": "R. Chavez",
    "u": "J. Martin",
    "h": "R. Robles",
    "l": "R. Klumph",
    "s": "K. Kronser",
    "f": "Z. Snell",
    "b": "B. Pettengill"
  },
  {
    "id": "544",
    "date": "10/13/2018",
    "site": "Cabrillo College",
    "home": "Cabrillo",
    "visitor": "Yuba",
    "r": "S. Carter",
    "u": "A. Gordillo",
    "h": "D. Johnson",
    "l": "D. Peterson",
    "s": "C. Coelho",
    "f": "M. Merritt",
    "b": "M. Dunn"
  },
  {
    "id": "545",
    "date": "10/13/2018",
    "site": "Chabot",
    "home": "Chabot",
    "visitor": "Diablo Valley",
    "r": "C. Miers",
    "u": "S. Jones",
    "h": "T. Welch",
    "l": "B. Werner",
    "s": "R. Maddox",
    "f": "C. Guinnip",
    "b": "M. Dominguez"
  },
  {
    "id": "609",
    "date": "10/13/2018",
    "site": "Sequoias (Mineral King Bowl)",
    "home": "Sequoias",
    "visitor": "Modesto",
    "r": "K. Blevens",
    "u": "B. Alcantar",
    "h": "D. Pepe",
    "l": "K. Govea",
    "s": "O. Salazar",
    "f": "B. Olesen",
    "b": "J. Bondi"
  },
  {
    "id": "546",
    "date": "10/19/2018",
    "site": "Diablo Valley",
    "home": "Diablo Valley",
    "visitor": "San Francisco",
    "r": "J. McGeough",
    "u": "A. Phillips",
    "h": "D. Dean",
    "l": "B. Werner",
    "s": "J. Decker",
    "f": "E. Joe",
    "b": "M. Dunn"
  },
  {
    "id": "547",
    "date": "10/19/2018",
    "site": "Laney",
    "home": "Laney",
    "visitor": "San Mateo",
    "r": "J. O'Neil",
    "u": "B. Collins",
    "h": "T. Bennett",
    "l": "D. Peterson",
    "s": "D. Evans",
    "f": "N. Stoll",
    "b": "J. Bondi"
  },
  {
    "id": "548",
    "date": "10/20/2018",
    "site": "Cabrillo College",
    "home": "Cabrillo",
    "visitor": "Gavilan",
    "r": "R. Mayabb",
    "u": "C. Hickman",
    "h": "L. Null",
    "l": "S. Ramos",
    "s": "H. Johnson",
    "f": "J. Mendoza",
    "b": "T. Brendlin"
  },
  {
    "id": "549",
    "date": "10/20/2018",
    "site": "Delta",
    "home": "Delta",
    "visitor": "Sequoias",
    "r": "J. Galvin",
    "u": "M. Tomlinson",
    "h": "D. Coelho",
    "l": "D. Dean",
    "s": "J. Springer",
    "f": "E. Joe",
    "b": "J. Freeman"
  },
  {
    "id": "550",
    "date": "10/20/2018",
    "site": "Foothill College",
    "home": "Foothill",
    "visitor": "Redwoods",
    "r": "D. Burch",
    "u": "B. O'Driscoll",
    "h": "R. Beeman",
    "l": "D. Pepe",
    "s": "J. Fugate",
    "f": "K. Thomas",
    "b": "J. Bigler"
  },
  {
    "id": "551",
    "date": "10/20/2018",
    "site": "Los Medanos",
    "home": "Los Medanos",
    "visitor": "Contra Costa",
    "r": "C. Miers",
    "u": "A. Gordillo",
    "h": "T. Welch",
    "l": "T. Bennett",
    "s": "E. Hawkins",
    "f": "A. Croskey",
    "b": "M. Merritt"
  },
  {
    "id": "552",
    "date": "10/20/2018",
    "site": "Sierra",
    "home": "Sierra",
    "visitor": "American River",
    "r": "K. Mason",
    "u": "A. Siderius",
    "h": "L. Weiper",
    "l": "J. Castagnola",
    "s": "C. Hayes",
    "f": "R. Maddox",
    "b": "K. Carver"
  },
  {
    "id": "553",
    "date": "10/20/2018",
    "site": "Siskiyous",
    "home": "Siskiyous",
    "visitor": "Butte",
    "r": "J. Johnson",
    "u": "J. Martin",
    "h": "C. Felkins",
    "l": "J. Kennedy",
    "s": "C. Hanna",
    "f": "B. Steinmann",
    "b": "J. Nagle"
  },
  {
    "id": "619",
    "date": "10/20/2018",
    "site": "Reedley (Reedley High School)",
    "home": "Reedley",
    "visitor": "San Jose",
    "r": "J. Taplin",
    "u": "L. Salazar",
    "h": "R. Clark",
    "l": "A. Garcia",
    "s": "J. Canales",
    "f": "B. Snyder",
    "b": "R. Cazares"
  },
  {
    "id": "554",
    "date": "10/20/2018",
    "site": "Sacramento",
    "home": "Sacramento",
    "visitor": "Fresno",
    "r": "R. Wright",
    "u": "M. Fagan",
    "h": "V. Wilson",
    "l": "B. Werner",
    "s": "C. Sindel",
    "f": "J. Mcclenahan",
    "b": "J. Bondi"
  },
  {
    "id": "555",
    "date": "10/20/2018",
    "site": "Feather River College",
    "home": "Feather River",
    "visitor": "Shasta",
    "r": "E. Hintz",
    "u": "E. Perez",
    "h": "A. Schmitz",
    "l": "T. Frugoli",
    "s": "G. Dieringer",
    "f": "T. Morris",
    "b": "R. Polito"
  },
  {
    "id": "556",
    "date": "10/20/2018",
    "site": "Santa Rosa Junior College",
    "home": "Santa Rosa",
    "visitor": "Chabot",
    "r": "M. Aldrich",
    "u": "D. Preciado",
    "h": "P. Llewellyn",
    "l": "S. Young",
    "s": "P. Schutt",
    "f": "A. Jensen",
    "b": "M. Fowler"
  },
  {
    "id": "557",
    "date": "10/20/2018",
    "site": "Monterey",
    "home": "Monterey",
    "visitor": "DeAnza",
    "r": "M. Younkin",
    "u": "M. Morris",
    "h": "D. Wood",
    "l": "L. Null",
    "s": "R. Davenport",
    "f": "T. Igbinedion",
    "b": "M. Dunn"
  },
  {
    "id": "602",
    "date": "10/20/2018",
    "site": "Hartnell (Rabobank Stadium)",
    "home": "Hartnell",
    "visitor": "Merced",
    "r": "S. Carter",
    "u": "S. Tate",
    "h": "D. Jones",
    "l": "R. Robeson",
    "s": "B. Olesen",
    "f": "D. Mullens",
    "b": "P. Campana"
  },
  {
    "id": "558",
    "date": "10/20/2018",
    "site": "Modesto",
    "home": "Modesto",
    "visitor": "West Hills",
    "r": "K. Udell",
    "u": "B. Alcantar",
    "h": "J. Brooks",
    "l": "J. Delgado",
    "s": "P. Robinson",
    "f": "O. Salazar",
    "b": "M. Dominguez"
  },
  {
    "id": "559",
    "date": "10/27/2018",
    "site": "Butte",
    "home": "Butte",
    "visitor": "American River",
    "r": "K. Leffle",
    "u": "T. Gomez",
    "h": "D. Dean",
    "l": "R. Robeson",
    "s": "J. Springer",
    "f": "R. Maddox",
    "b": "J. Nagle"
  },
  {
    "id": "560",
    "date": "10/27/2018",
    "site": "Contra Costa",
    "home": "Contra Costa",
    "visitor": "Foothill",
    "r": "M. Aldrich",
    "u": "B. Wilson",
    "h": "V. Wilson",
    "l": "P. Llewellyn",
    "s": "E. Hawkins",
    "f": "P. Schutt",
    "b": "T. Brendlin"
  },
  {
    "id": "561",
    "date": "10/27/2018",
    "site": "DeAnza",
    "home": "DeAnza",
    "visitor": "Los Medanos",
    "r": "M. Younkin",
    "u": "M. Tomlinson",
    "h": "D. Coelho",
    "l": "K. Govea",
    "s": "R. Davenport",
    "f": "T. Igbinedion",
    "b": "M. Dunn"
  },
  {
    "id": "562",
    "date": "10/27/2018",
    "site": "Delta",
    "home": "Delta",
    "visitor": "Sacramento",
    "r": "E. Hintz",
    "u": "A. Siderius",
    "h": "T. Frugoli",
    "l": "J. Delgado",
    "s": "J. Mendoza",
    "f": "P. Robinson",
    "b": "K. Carver"
  },
  {
    "id": "563",
    "date": "10/27/2018",
    "site": "Redwoods",
    "home": "Redwoods",
    "visitor": "Yuba",
    "r": "K. Mason",
    "u": "D. Wellington",
    "h": "L. Weiper",
    "l": "J. Castagnola",
    "s": "S. Young",
    "f": "C. Hayes",
    "b": "E. Hirsch"
  },
  {
    "id": "564",
    "date": "10/27/2018",
    "site": "San Francisco City College",
    "home": "San Francisco",
    "visitor": "Chabot",
    "r": "B. Michelson",
    "u": "P. Burford",
    "h": "T. Bennett",
    "l": "D. Jones",
    "s": "A. Croskey",
    "f": "K. Thomas",
    "b": "M. Fowler"
  },
  {
    "id": "565",
    "date": "10/27/2018",
    "site": "San Jose",
    "home": "San Jose",
    "visitor": "Cabrillo",
    "r": "S. Carter",
    "u": "A. Gordillo",
    "h": "D. Johnson",
    "l": "C. Coelho",
    "s": "D. Mullens",
    "f": "B. Olesen",
    "b": "J. Bondi"
  },
  {
    "id": "566",
    "date": "10/27/2018",
    "site": "San Mateo",
    "home": "San Mateo",
    "visitor": "Diablo Valley",
    "r": "M. Merritt",
    "u": "B. Alcantar",
    "h": "R. Beeman",
    "l": "D. Pepe",
    "s": "D. Evans",
    "f": "N. Stoll",
    "b": "O. Sangameswara"
  },
  {
    "id": "567",
    "date": "10/27/2018",
    "site": "Sierra",
    "home": "Sierra",
    "visitor": "Feather River",
    "r": "K. Udell",
    "u": "E. Perez",
    "h": "M. Averett",
    "l": "J. Kennedy",
    "s": "J. Rogers",
    "f": "B. Steinmann",
    "b": "M. Dominguez"
  },
  {
    "id": "568",
    "date": "10/27/2018",
    "site": "West Hills",
    "home": "West Hills",
    "visitor": "Sequoias",
    "r": "J. Taplin",
    "u": "L. Salazar",
    "h": "R. Clark",
    "l": "C. Burrell",
    "s": "J. Canales",
    "f": "D. Burch",
    "b": "R. Cazares"
  },
  {
    "id": "603",
    "date": "10/27/2018",
    "site": "Fresno (Radcliffe Stadium)",
    "home": "Fresno",
    "visitor": "Modesto",
    "r": "C. Miers",
    "u": "M. Morris",
    "h": "L. Mcinerney",
    "l": "S. Ramos",
    "s": "T. Pinedo",
    "f": "B. Snyder",
    "b": "J. Freeman"
  },
  {
    "id": "569",
    "date": "10/27/2018",
    "site": "Santa Rosa Junior College",
    "home": "Santa Rosa",
    "visitor": "Laney",
    "r": "G. Robinson",
    "u": "B. Collins",
    "h": "________ ",
    "l": "A. Garcia",
    "s": "N. Pontecorvo",
    "f": "________ ",
    "b": "P. Campana"
  },
  {
    "id": "570",
    "date": "10/27/2018",
    "site": "Merced",
    "home": "Merced",
    "visitor": "Reedley",
    "r": "K. Blevens",
    "u": "M. Fagan",
    "h": "P. Farley",
    "l": "B. Werner",
    "s": "C. Guinnip",
    "f": "K. Heard",
    "b": "D. Velleman"
  },
  {
    "id": "571",
    "date": "10/27/2018",
    "site": "Monterey",
    "home": "Monterey",
    "visitor": "Hartnell",
    "r": "R. Mayabb",
    "u": "T. Sparkes",
    "h": "R. Nelson",
    "l": "D. Peterson",
    "s": "H. Johnson",
    "f": "O. Salazar",
    "b": "A. Smart"
  },
  {
    "id": "572",
    "date": "10/27/2018",
    "site": "Shasta",
    "home": "Shasta",
    "visitor": "Siskiyous",
    "r": "R. Chavez",
    "u": "A. Phillips",
    "h": "R. Klumph",
    "l": "R. Robles",
    "s": "J. Johnson",
    "f": "K. Kronser",
    "b": "B. Pettengill"
  },
  {
    "id": "573",
    "date": "11/2/2018",
    "site": "Diablo Valley",
    "home": "Diablo Valley",
    "visitor": "Laney",
    "r": "M. Merritt",
    "u": "S. Tate",
    "h": "P. Llewellyn",
    "l": "R. Robeson",
    "s": "A. Jensen",
    "f": "J. Decker",
    "b": "J. Bondi"
  },
  {
    "id": "574",
    "date": "11/3/2018",
    "site": "Butte",
    "home": "Butte",
    "visitor": "Sierra",
    "r": "R. Wright",
    "u": "A. Phillips",
    "h": "R. Klumph",
    "l": "R. Robles",
    "s": "Z. Snell",
    "f": "K. Kronser",
    "b": "J. Aragon"
  },
  {
    "id": "575",
    "date": "11/3/2018",
    "site": "Cabrillo College",
    "home": "Cabrillo",
    "visitor": "Merced",
    "r": "M. Younkin",
    "u": "B. Collins",
    "h": "D. Jones",
    "l": "L. Mcinerney",
    "s": "R. Davenport",
    "f": "T. Igbinedion",
    "b": "O. Sangameswara"
  },
  {
    "id": "576",
    "date": "11/3/2018",
    "site": "Foothill College",
    "home": "Foothill",
    "visitor": "DeAnza",
    "r": "B. Michelson",
    "u": "M. Fagan",
    "h": "M. Aldrich",
    "l": "D. Johnson",
    "s": "K. Heard",
    "f": "J. Mendoza",
    "b": "M. Dominguez"
  },
  {
    "id": "577",
    "date": "11/3/2018",
    "site": "San Francisco City College",
    "home": "San Francisco",
    "visitor": "Santa Rosa",
    "r": "J. McGeough",
    "u": "A. Siderius",
    "h": "J. Castagnola",
    "l": "L. Weiper",
    "s": "G. Dieringer",
    "f": "C. Hayes",
    "b": "M. Dunn"
  },
  {
    "id": "578",
    "date": "11/3/2018",
    "site": "Siskiyous",
    "home": "Siskiyous",
    "visitor": "Feather River",
    "r": "C. Miers",
    "u": "M. Tomlinson",
    "h": "S. Young",
    "l": "V. Wilson",
    "s": "C. Guinnip",
    "f": "E. Joe",
    "b": "J. Freeman"
  },
  {
    "id": "579",
    "date": "11/3/2018",
    "site": "West Hills",
    "home": "West Hills",
    "visitor": "Delta",
    "r": "J. O'Neil",
    "u": "C. Hickman",
    "h": "T. Bennett",
    "l": "R. Nelson",
    "s": "N. Stoll",
    "f": "D. Evans",
    "b": "A. Smart"
  },
  {
    "id": "580",
    "date": "11/3/2018",
    "site": "Yuba",
    "home": "Yuba",
    "visitor": "Contra Costa",
    "r": "R. Chavez",
    "u": "S. Jones",
    "h": "J. Kennedy",
    "l": "C. Felkins",
    "s": "C. Hanna",
    "f": "B. Steinmann",
    "b": "K. Erskine"
  },
  {
    "id": "581",
    "date": "11/3/2018",
    "site": "American River College",
    "home": "American River",
    "visitor": "Shasta",
    "r": "J. Galvin",
    "u": "M. Morris",
    "h": "M. Averett",
    "l": "T. Frugoli",
    "s": "J. Johnson",
    "f": "J. Mcclenahan",
    "b": "P. Campana"
  },
  {
    "id": "620",
    "date": "11/3/2018",
    "site": "Reedley (Reedley High School)",
    "home": "Reedley",
    "visitor": "Monterey",
    "r": "J. Taplin",
    "u": "T. Sparkes",
    "h": "D. Dean",
    "l": "T. Welch",
    "s": "K. Blevens",
    "f": "B. Snyder",
    "b": "R. Cazares"
  },
  {
    "id": "615",
    "date": "11/3/2018",
    "site": "Gavilan (Gilroy High School)",
    "home": "Gavilan",
    "visitor": "San Jose",
    "r": "K. Leffle",
    "u": "L. Salazar",
    "h": "J. Delgado",
    "l": "A. Garcia",
    "s": "A. Croskey",
    "f": "O. Salazar",
    "b": "M. Fowler"
  },
  {
    "id": "604",
    "date": "11/3/2018",
    "site": "Hartnell (Rabobank Stadium)",
    "home": "Hartnell",
    "visitor": "Los Medanos",
    "r": "S. Carter",
    "u": "A. Gordillo",
    "h": "J. Brooks",
    "l": "S. Ramos",
    "s": "T. Pinedo",
    "f": "P. Robinson",
    "b": "R. Medeiros"
  },
  {
    "id": "582",
    "date": "11/3/2018",
    "site": "Chabot",
    "home": "Chabot",
    "visitor": "San Mateo",
    "r": "G. Robinson",
    "u": "D. Preciado",
    "h": "P. Llewellyn",
    "l": "D. Wood",
    "s": "D. Velleman",
    "f": "A. Jensen",
    "b": "J. Nardi"
  },
  {
    "id": "583",
    "date": "11/3/2018",
    "site": "Modesto",
    "home": "Modesto",
    "visitor": "Sacramento",
    "r": "K. Mason",
    "u": "D. Wellington",
    "h": "R. Beeman",
    "l": "B. Werner",
    "s": "C. Sindel",
    "f": "J. Springer",
    "b": "E. Hirsch"
  },
  {
    "id": "610",
    "date": "11/3/2018",
    "site": "Sequoias (Mineral King Bowl)",
    "home": "Sequoias",
    "visitor": "Fresno",
    "r": "J. Bigler",
    "u": "B. Alcantar",
    "h": "C. Burrell",
    "l": "D. Pepe",
    "s": "D. Mullens",
    "f": "B. Olesen",
    "b": "J. Bondi"
  },
  {
    "id": "584",
    "date": "11/9/2018",
    "site": "Laney",
    "home": "Laney",
    "visitor": "Chabot",
    "r": "S. Carter",
    "u": "T. Daurelio",
    "h": "R. Nelson",
    "l": "T. Welch",
    "s": "T. Brendlin",
    "f": "J. Decker",
    "b": "M. Dunn"
  },
  {
    "id": "585",
    "date": "11/10/2018",
    "site": "DeAnza",
    "home": "DeAnza",
    "visitor": "Yuba",
    "r": "K. Udell",
    "u": "L. Salazar",
    "h": "C. Burrell",
    "l": "K. Govea",
    "s": "P. Robinson",
    "f": "T. Pinedo",
    "b": "M. Dunn"
  },
  {
    "id": "586",
    "date": "11/10/2018",
    "site": "Delta",
    "home": "Delta",
    "visitor": "Modesto",
    "r": "________ ",
    "u": "S. Tate",
    "h": "J. Kennedy",
    "l": "D. Jones",
    "s": "D. Mullens",
    "f": "K. Thomas",
    "b": "J. Nagle"
  },
  {
    "id": "587",
    "date": "11/10/2018",
    "site": "Los Medanos",
    "home": "Los Medanos",
    "visitor": "Foothill",
    "r": "G. Robinson",
    "u": "M. Morris",
    "h": "R. Medeiros",
    "l": "P. Llewellyn",
    "s": "C. Sindel",
    "f": "J. Springer",
    "b": "T. Brendlin"
  },
  {
    "id": "588",
    "date": "11/10/2018",
    "site": "Merced",
    "home": "Merced",
    "visitor": "Gavilan",
    "r": "R. Mayabb",
    "u": "S. Jones",
    "h": "D. Pepe",
    "l": "A. Juarez",
    "s": "H. Johnson",
    "f": "O. Salazar",
    "b": "J. Aragon"
  },
  {
    "id": "589",
    "date": "11/10/2018",
    "site": "San Jose",
    "home": "San Jose",
    "visitor": "Redwoods",
    "r": "B. Michelson",
    "u": "C. Hickman",
    "h": "S. Ramos",
    "l": "M. Merritt",
    "s": "E. Hawkins",
    "f": "J. Fugate",
    "b": "O. Sangameswara"
  },
  {
    "id": "590",
    "date": "11/10/2018",
    "site": "San Mateo",
    "home": "San Mateo",
    "visitor": "San Francisco",
    "r": "M. Aldrich",
    "u": "D. Preciado",
    "h": "D. Dean",
    "l": "L. Null",
    "s": "J. Johnson",
    "f": "D. Velleman",
    "b": "P. Campana"
  },
  {
    "id": "591",
    "date": "11/10/2018",
    "site": "Sierra",
    "home": "Sierra",
    "visitor": "Siskiyous",
    "r": "J. Galvin",
    "u": "B. Collins",
    "h": "D. Coelho",
    "l": "L. Mcinerney",
    "s": "T. Morris",
    "f": "P. Schutt",
    "b": "J. Freeman"
  },
  {
    "id": "605",
    "date": "11/10/2018",
    "site": "Fresno (Radcliffe Stadium)",
    "home": "Fresno",
    "visitor": "West Hills",
    "r": "K. Blevens",
    "u": "B. Wilson",
    "h": "J. Delgado",
    "l": "A. Garcia",
    "s": "N. Pontecorvo",
    "f": "J. Mendoza",
    "b": "R. Cazares"
  },
  {
    "id": "593",
    "date": "11/10/2018",
    "site": "Feather River College",
    "home": "Feather River",
    "visitor": "American River",
    "r": "E. Hintz",
    "u": "A. Siderius",
    "h": "M. Averett",
    "l": "A. Schmitz",
    "s": "J. Mcclenahan",
    "f": "R. Polito",
    "b": "K. Carver"
  },
  {
    "id": "594",
    "date": "11/10/2018",
    "site": "Santa Rosa Junior College",
    "home": "Santa Rosa",
    "visitor": "Diablo Valley",
    "r": "K. Leffle",
    "u": "P. Burford",
    "h": "J. Castagnola",
    "l": "L. Weiper",
    "s": "A. Croskey",
    "f": "S. Young",
    "b": "E. Hirsch"
  },
  {
    "id": "595",
    "date": "11/10/2018",
    "site": "Monterey",
    "home": "Monterey",
    "visitor": "Cabrillo",
    "r": "D. Burch",
    "u": "B. Alcantar",
    "h": "D. Peterson",
    "l": "D. Wood",
    "s": "R. Davenport",
    "f": "B. Olesen",
    "b": "J. Bondi"
  },
  {
    "id": "596",
    "date": "11/10/2018",
    "site": "Shasta",
    "home": "Shasta",
    "visitor": "Butte",
    "r": "R. Chavez",
    "u": "M. Tomlinson",
    "h": "R. Klumph",
    "l": "R. Robles",
    "s": "C. Hanna",
    "f": "Z. Snell",
    "b": "B. Pettengill"
  },
  {
    "id": "606",
    "date": "11/10/2018",
    "site": "Hartnell (Rabobank Stadium)",
    "home": "Hartnell",
    "visitor": "Reedley",
    "r": "M. Younkin",
    "u": "B. O'Driscoll",
    "h": "P. Farley",
    "l": "D. Johnson",
    "s": "D. Evans",
    "f": "N. Stoll",
    "b": "A. Smart"
  },
  {
    "id": "592",
    "date": "11/11/2018",
    "site": "Sacramento",
    "home": "Sacramento",
    "visitor": "Sequoias",
    "r": "________ ",
    "u": "M. Fagan",
    "h": "________ ",
    "l": "J. Delgado",
    "s": "P. Robinson",
    "f": "M. Merritt",
    "b": "J. Freeman"
  }
]

module.exports = {data: games}